board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:board_id>/', views.detail, name='detail'),
    path('write/', views.write, name='write'),
    path('write/write_board', views.write_board, name='write_board'),
    path('<int:board_id>/create_reply', views.create_reply, name='create_reply'),
]

testyou/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [ #수정조금
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
]

board/models.py
from django.db import models

class Board(models.Model):
    """
    title:제목
    content:내용
    author:작성자
    like_count:좋아요 카운트
    pub_date:배포일
    """
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=500)
    author = models.CharField(max_length=100)
    like_count = models.PositiveIntegerField(default=0) #양수입력 필드
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.title

class Reply(models.Model):
    """
        reply:Reply -> Board 연결관계
        comment: 댓글내용
        rep_date: 작성일
    """
    reply = models.ForeignKey(Board, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    rep_date = models.DateTimeField()

    def __str__(self):
        return self.comment

board/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.utils import timezone
from django.urls import reverse

from .models import Board

# 인덱스 뷰 테스트
# def index(request):
#     context = {
#         'title': 'Board list',
#         'board_list': [
#             {'no':1, 'title': '목록1'},
#             {'no':2, 'title': '목록2'},
#             {'no':3, 'title': '목록3'},
#             {'no':4, 'title': '목록4'},
#             {'no':5, 'title': '목록5'},
#         ]
#     }
#     return render(request, 'board/index.html', context)
from django.core.paginator import Paginator

def index(request): #게시글 목록
    all_boards = Board.objects.all().order_by("-pub_date") #모든 데이터 조회, 내침차순(-표시) 조회
    paginator = Paginator(all_boards, 5)  #글을 5개씩 출력
    page = int(request.GET.get('page', 1)) # index로 GET요청이 들어올시 page 파라메타를 읽는다  없는경우 디폴트로 1번째 페이지
    board_list = paginator.get_page(page)

    return render(request, 'board/index.html', {'title':'Board List', 'board_list':all_boards})

def detail(request, board_id): #상세페이지
    board = Board.objects.get(id=board_id)
    return render(request, 'board/detail.html', {'board': board})

def write(request): #글쓰기
    return render(request, 'board/write.html')

def write_board(request): #글을 등록시 submit처리
    b = Board(title=request.POST['title'], content=request.POST['detail'], author="choi", pub_date=timezone.now())
    b.save()
    return HttpResponseRedirect(reverse('board:index'))

def create_reply(request, board_id): #댓글 submit 처리
    b = Board.objects.get(id = board_id)
    b.reply_set.create(comment=request.POST['comment'], rep_date=timezone.now())
    return HttpResponseRedirect(reverse('board:detail', args=(board_id,)))

board/templates/board/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style type="text/css">
        .content {
            max-width:500px;
            margin: auto;
            padding:10px;
        }

		.reply_content {
			text-align:right
		}

		.reply_content .reply{
			border-radius: 0.5em;
			display: block;
			margin: 4px;
			padding: 3px 10px;
		}

		.board_for_read {
			width: 100%;
			background-color:#f1f1f1;
		}

		#title {
			height: 32px;
			width: 100%;
			border-radius: 0.5em;
			border: none;
			font-family: inherit;
			font-size: inherit;
			background: none;
		}

        textarea {
			width: 100%;
            font-family: inherit;
            font-size: 100%;
			resize: none;
			border-radius: 0.5em;
			padding-block: 10px;
			border: 0px;
			background: none;
        }

		.td_title {
			background-color: #d8d8d8
		}
    </style>
<body>
    <div class="content">

		<table class="board_for_read">
			<tbody>
				<tr>
					<td class="td_title" style="text-align:center; width:20%;">제목</td>
					<td style="padding:10px;">
						<input type="text" name="title" id="title" value="{{ board.title }}" readonly/>
					</td>
				</tr>
				<tr>
					<td class="td_title" style="text-align:center; width:20%;">작성일자</td>
					<td style="padding:10px;">
						<span>{{ board.pub_date }}</span>
					</td>
				</tr>
				<tr>
					<td class="td_title" style="text-align:center;">내용</td>
					<td style="padding:10px;">
						<textarea name="detail" id="detail" rows="10" readonly>{{ board.content }}</textarea>
					</td>
				</tr>
			</tbody>
		</table>
		<div style="text-align:left;">
			<a href="{% url 'board:index' %}">> Home</a>
		</div>

		<form action="{% url 'board:create_reply' board.id %}" method="post">
		{% csrf_token %}
		<table class="board_for_read">
			<tbody>
				<tr>
					<td colspan="2" class="td_title" style="text-align:left; padding-left:10px; height:30px;">leave a comment</td>
				</tr>
				<tr>
					<td style="text-align:center;">
						<input type="text" name="comment" id="comment" style="width:100%">
					</td>
					<td><input type="submit" value="save"></td>
				</tr>
			</tbody>
		</table>
		</form>

		<div class="reply_content">
			{% for rep in board.reply_set.all %}
				<span class="reply">{{ rep.comment }} [{{ rep.rep_date|date:'Y-m-d H:i'}}]</span>
			{% endfor %}
		</div>
    </div>
</body>
</html>

board/templates/board/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MY Board</title>
</head>
<style type="text/css">
        thead {
            background-color:#cecece;
        }

        .content {
            max-width:500px;
            margin: auto;
            padding:10px;
        }

        .header {
            text-align: center;
        }

        .board {
            width: 100%
        }

        .even_bgcolor {
            background-color:#e8efff;
        }

        .pagination {
            display: flex;
        }

        .current {
            font-weight: bold;
        }

        a {
            text-decoration: none;
            text-align: center;
        }

        .abutton {
            background-color: #e6e6ff;
            color: #7b7b7b;
            font-size: small;
        }

    </style>
<body>
    <div class="content">
        <div class="header">
            <h2>{{ title }}</h2>
        </div>
        <div style="text-align:right">
            <a href="{% url 'board:write' %}">글쓰기</a>
        </div>

        <div style="height:280px;">
            <table class="board">
                <thead>
                    <tr class="header">
                        <th style="width:10%;">순번</th>
                        <th style="width:60%">제목</th>
                        <th style="width:30%">작성일자</th>
                    </tr>
                </thead>
                <tbody>
                {% if board_list %}
                    {% for data in board_list %}
                    <tr class="{% cycle '' 'even_bgcolor' %}">
                        <td style="text-align:center;">{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'board:detail' data.id %}">
                                {{ data.title }}
                            </a>
                        </td>
                        <td>{{ data.pub_date|date:'Y-m-d' }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>작성된 게시글이 없습니다.</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>

        <!-- Pagination -->
        <div style="text-align:center">
            <div class="pagination">

                <div style="width:35%; margin: 5px;">
                {% if board_list.has_previous %}
                    <a class="abutton" href="?page=1">맨 앞으로</a>
                    <a class="abutton" href="?page={{ board_list.previous_page_number }}">이전</a>
                {% endif %}
                </div>

                <div style="width:30%; margin: 5px;">
                {% for page in board_list.paginator.page_range %}
                    {% if page >= board_list.number|add:-2 and page <= board_list.number|add:2 %}
                    <span class="{% if page == board_list.number %}current{% endif %}">
                        <a href="?page={{ page }}">{{ page}}</a>
                    </span>
                    {% elif page >= board_list.number|add:-3 and page <= board_list.number|add:3 %}
                        ..
                    {% endif %}
                {% endfor %}
                </div>

                <div style="width:35%; margin: 5px;">
                {% if board_list.has_next %}
                    <a class="abutton" href="?page={{ board_list.next_page_number }}">다음</a>
                    <a class="abutton" href="?page={{ board_list.paginator.num_pages }}">맨 뒤로</a>
                {% endif %}
                </div>

            </div>
        </div>
    </div>
</body>
</html>

board/templates/board/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style type="text/css">
        .content {
            max-width:500px;
            margin: auto;
            padding:10px;
        }

		.board_for_read {
			width: 100%;
			background-color:#f1f1f1;
		}

		#title {
			height: 32px;
			width: 100%;
			border-radius: 0.5em;
			border: none;
			font-family: inherit;
			font-size: inherit;
		}

        textarea {
			width: 100%;
            font-family: inherit;
            font-size: 100%;
			resize: none;
			border-radius: 0.5em;
			padding-block: 10px;
			border: 0px;
        }

		.td_title {
			background-color: #d8d8d8
		}
    </style>
<body>
	<div class="content">
        <div class="header", style="text-align:center">
            <h2>글 작성</h2>
        </div>
    <div class="content">
		<form action="{% url 'board:write_board' %}" method="post">
		{% csrf_token %}

		<div style="text-align:right;padding: 5px;">
			<input type="submit" value="저장">
		</div>

		<table class="board_for_read">
			<tbody>
				<tr>
					<td class="td_title" style="text-align:center; width:20%;">제목</td>
					<td style="padding:10px;">
						<input type="text" name="title" id="title" value="{{ board.title }}"/>
					</td>
				</tr>
				<tr>
					<td class="td_title" style="text-align:center;">내용</td>
					<td style="padding:10px;">
						<textarea name="detail" id="detail" rows="10">{{ board.content }}</textarea>
					</td>
				</tr>
			</tbody>
		</table>
		</form>

		<div style="text-align:left;">
			<a href="{% url 'board:index' %}">> Home</a>
		</div>

    </div>
</body>
</html>